<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>
<?php
$block = $this->getBlock();
$_isCheckHome = $block->getLayout()->createBlock('\Magento\Theme\Block\Html\Header\Logo')->isHomePage();
?>
<div class="footer-container">

    <?php if ($helper->getStoreConfig('mgstheme/general/header') == 'header_2'): ?>
            <?php if ($_isCheckHome == false): ?>
            <section class="top-footer">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_newsletter_footer')->setCanUsePanel($canUsePanel)->toHtml() ?>
            </section>
        <?php endif; ?>
        <?php else: ?>
        <section class="top-footer">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_newsletter_footer')->setCanUsePanel($canUsePanel)->toHtml() ?>
        </section>
<?php endif; ?>

    <section class="middle-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-12 col-xs-12">
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_info_ft')->setCanUsePanel($canUsePanel)->toHtml() ?>
                </div>

                <div class="col-md-3 col-sm-12 col-xs-12">
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organice_account_ft')->setCanUsePanel($canUsePanel)->toHtml() ?>
                </div>
                <div class="col-md-3 col-sm-12 col-xs-12">
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_widget_flickr')->setCanUsePanel($canUsePanel)->toHtml() ?>
                </div>
                <div class="col-md-3 col-sm-12 col-xs-12">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_contact_ft')->setCanUsePanel($canUsePanel)->toHtml() ?>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('organie_social')->setCanUsePanel($canUsePanel)->toHtml() ?>
                </div>
            </div>
        </div>
    </section>
    <section class="bottom-footer">
        <div class="container">
            <div class="bottom-ft-container">
                <div class="row">

                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>

                </div>
            </div>
        </div>
    </section>
</div>
