<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>

<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>" data-mage-init='{"bundleSlider":{}}'>

    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()) : ?>
            <input type="hidden"
                   class="bundle-option-<?= (int)$_option->getId() ?>  product bundle option"
                   name="bundle_option[<?= (int)$_option->getId() ?>]"
                   value="<?= (int)$_selections[0]->getSelectionId() ?>"
                   id="bundle-option-<?= (int)$_option->getId() ?>-<?= (int)$_selections[0]->getSelectionId() ?>"
                   checked="checked"
            />
            <?php else :?>
                <label class="label">
                    <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
                </label>
            <?php if (!$_option->getRequired()) : ?>
                <div class="field choice">
                    <input type="radio"
                           class="radio product bundle option"
                           id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                           name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                           data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                        <?= ($_default && $_default->isSalable())?'':' checked="checked" ' ?>
                           value=""/>
                    <label class="label" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>">
                        <span><?= $block->escapeHtml(__('None')) ?></span>
                    </label>
                </div>
            <?php endif; ?>
                <ol class="bundle-option-slider">
                    <?php foreach ($_selections as $_selection) : ?>
                        <li class="field choice">
                            <?php
                            $_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
                            $blockName = $block->getNameInLayout();
                            $blockName = str_replace("\\", "_", $blockName);
                            $image = $_imageHelper->init($_selection, 'small_image', ['type' => 'small_image'])->keepAspectRatio(true)->resize('200', '200')->getUrl(); ?>
                            <input type="radio"
                                   class="radio product bundle option change-container-classname radio-price"
                                   id="<?=$blockName?>-bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                                <?php if ($_option->getRequired()) { echo 'data-validate="{\'validate-one-required-by-name\':true}"'; }?>
                                   name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]-<?=$blockName?>"
                                   data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                                <?php if ($block->isSelected($_selection)) { echo ' checked="checked"'; } ?>
                                   value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                                   data-in-stock="<?php echo $_selection->getIsSalable() ? 'true' : 'false' ?>"
                                    data-mage-init='{"bundleOptionSelect":{}}'/>

                            <label class="label"
                                   for="<?=$blockName?>-bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>">
                                <span><?= /* @noEscape */ $block->getSelectionTitlePrice($_selection) ?></span>
                                <br/>

                                <div class="bundle-option-image" id="bundle-image-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"><img src="<?php echo $image; ?>" /></div>
                            </label>

                        </li>
                    <?php endforeach; ?>
                </ol>
                <!-- Place holder -->
                <input class="hidden-input" name="bundlespot" value="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"/>
                <!--// Place holder -->

                <div id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></div>
            <?php endif; ?>

            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                    <span><?= $block->escapeHtml(__('Quantity')) ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?>
                            id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                            class="input-text qty<?php if (!$_canChangeQty) { echo ' qty-disabled'; } ?>"
                            type="number"
                            name="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                            data-selector="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                            value="<?= $block->escapeHtmlAttr($_defaultQty) ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>
