<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $helper \Smartosc\CustomBundleProduct\Helper\Data */
?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder();
$helper = $this->helper('Smartosc\CustomBundleProduct\Helper\Data');
$qtyOrdered = (int)$_item->getQty();
$isReportServiceProduct = $helper->isReportServiceProduct($_item->getProductId()) && $qtyOrdered < 1;
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= $isReportServiceProduct ? '' : (float) $_item->getQty() ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $isReportServiceProduct ? __('Not Require') : $block->getItemPrice($_item->getOrderItem()) ?>
    </td>
</tr>
