<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

/** @var \Smartosc\CustomBundleProduct\Helper\CartItemHelper $addonHelper */
$addonHelper = $this->helper(\Smartosc\CustomBundleProduct\Helper\CartItemHelper::class);
?>

<tbody class="cart <?= $addonHelper->isAddonItemId($_item->getId()) ? 'addon-item' : 'item' ?>">
    <tr class="item-info">
        <td data-th="<?php echo $block->escapeHtml(__('Product')); ?>" class="col item">
            <?php if ($block->hasProductUrl()): ?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                   title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else: ?>
                <span class="product-item-photo">
            <?php endif; ?>
            <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php if ($block->hasProductUrl()): ?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>

            <div class="product-item-details">
                <h4 class="product-item-name">
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </h4>

                <dl class="product-item-code">
                    <dt><?= __('Item Code:') ?></dt>
                    <dd><?= $_item->getSku(); ?></dd>
                </dl>

                <?php if ($_options = $block->getOptionList()): ?>
                    <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
                <div class="actions-toolbar">
                    <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
                </div>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <span class="pricing msrp">
                <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId; ?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                    <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                </a>
            </span>
        </td>
        <?php else: ?>
        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getUnitPriceHtml($_item); ?>
        </td>
        <?php endif; ?>

        <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                    <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                </label>
                <div class="control qty">
                    <span class="edit-qty minus" data-role="minusAction-cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><i class="ion-ios-minus-outline"></i></span>
                    <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                        data-id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                        name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                        data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                        value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                        type="number"
                        size="4"
                        title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                        class="input-text qty input-qty"
                        maxlength="12"
                        data-validate='{"required-number":true, "validate-item-quantity":{"minAllowed":0, "maxAllowed":10000}}'
                        data-role="cart-item-qty"/>
                        <span class="edit-qty plus" data-role="plusAction-cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><i class="ion-ios-plus-outline"></i></span>
                </div>
            </div>
        </td>


        <td class="col discount" data-th="<?php echo $block->escapeHtml(__('Discount')); ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp discount">--</span>
        <?php else: ?>
            <span class="cart-items-discount" style="font-size:18px;padding-top:0;"><?php echo $block->convertPrice($_item->getDiscountAmount(),true); ?></span>
        <?php endif; ?>
        </td>

        <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Total')); ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?php echo $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
        </td>

        <td class="actions">
            <div class="actions-toolbar hidden-xs">
                <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>

<script type="text/x-magento-init">
        {
            ".form.form-cart": {
                "quantityCart": {}
            }
        }
    </script>
