<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$orders = $objectManager->create('Magento\Checkout\Model\Cart');
$allItem = $orders->getQuote()->getItems();
$qty = 0;

if (is_array($allItem) || is_object($allItem)) {
    foreach ($allItem as $item) {
        if ($block->getData('product_name')== $item->getName()) {
            $qty = $item->getQty();
        }
    }
}
?>

<?= $block->escapeHtml(__(
    'You added %1 items %2 to your <a href="%2">shopping cart</a>.',
    $qty,
    $block->getData('product_name'),
    $block->getData('cart_url')
), ['a']);
